# XPU Device Configuration File
# Format: vendor_id device_id plugin_name [description]
#
# NVIDIA GPUs
0x10de 0x2231 cuda    # NVIDIA RTX A5000
0x10de 0x20f1 cuda    # NVIDIA A100
0x10de 0x2685 cuda    # NVIDIA GeForce RTX 4090 D
0x10de 0x2684 cuda    # NVIDIA GeForce RTX 4090
0x10de 0x2702 cuda    # NVIDIA GeForce RTX 4080
0x10de 0x2704 cuda    # NVIDIA GeForce RTX 4080
0x10de 0x2503 cuda    # NVIDIA GeForce RTX 3060
0x10de 0x2504 cuda    # NVIDIA GeForce RTX 3060
0x10de 0x2507 cuda    # NVIDIA GeForce RTX 3050
0x10de 0x2508 cuda    # NVIDIA GeForce RTX 3050 OEM
0x10de 0x21c4 cuda    # NVIDIA GeForce GTX 1660 SUPER
0x10de 0x2b87 cuda    # NVIDIA GeForce GTX 5090d

# AMD GPUs
0x1002 0x744c hip     # AMD Radeon RX 7900 XTX
0x1002 0x7550 hip     # AMD Radeon RX 9070

# Hygon DCU
0x1d94 0x6210 hip     # Hygon KONGMING DCU

# Intel GPUs
0x8086 0x7d55 sycl    # Intel Arc Graphics

# Rpp NPU
0x1f2e 0x00c1 rpp     # RPP Device

# Glenfly GPUs
0x6766 0x3d06 ponn    # Glenfly Arise-GT-10C0t
0x6766 0x3d07 ponn    # Glenfly Arise-GT-2030

# 
